About/urls.py
from django.conf.urls import url
from .views import (About,)

app_name = 'about'

urlpatterns = [
    url(r'^$', About.as_view(), name="about"),
]

CreateCard/urls.py
from django.conf.urls import url, include
from .views import (Index,
                    ViewCard)

app_name = 'create-card'

urlpatterns = [
    url(r'^$', Index.as_view(), name='index'),
    url(r'^view-card$', ViewCard.as_view(), name="view"),
]

Test/urls.py
from django.conf.urls import url, include
from .views import Test

app_name = 'test'

urlpatterns = [
    # for testing purpose only
    url(r'^$', Test.as_view(), name='test')
]

ToDo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #App Urls
    url(r'^create-card/', include('CreateCard.urls')),
    url(r'^about/', include('About.urls')),
    url(r'^test/', include('Test.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

About/models.py
from django.db import models

# Create your models here.

CreateCard/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.timezone import now
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
import re

def length_validator(seq):
    if len(seq) != 13:
        raise ValidationError(
            _('Provided number is not a valid number'),
        )

message = "Please enter a valid 10 digit number. Do not use +91."
regex = r'^+91[0-9]{10}'
regex_validator = RegexValidator(regex=regex, message=message)

# Create your models here.
class ToDoModel(models.Model):
    name = models.CharField(max_length=40)
    time = models.DateTimeField()
    to_do = models.TextField()
    phone_number = models.CharField(max_length=13, validators=[regex_validator, length_validator])


    def __str__(self):
        return self.to_do

Test/models.py
from django.db import models

# Create your models here.

About/forms.py
from django import forms
from .models import ToDoModel
from django.contrib.auth.models import User
from django.contrib.auth.forms import (UserChangeForm,)

class UserCreationForm(UCF):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        help_texts = {
            'username': 'Only alphaNumeric characters are allowed in combination with @#!()*',
            'email': None,
        }

About/views.py
from django.shortcuts import render
from django.views import View
# Create your views here.

class About(View):
    def get(self, request, *args, **kwargs):
        signup_form = UserCreationForm()
        context = {
        "signup_form":signup_form,
        }
        return render(request, 'about.html', context)

    def post(self, request, *args, **kwargs):
        signup_form = UserCreationForm(request.POST or None)
        
        if signup_form.is_valid():
            instance = signup_form.save()
            auth_login(request, instance)
            return HttpResponseRedirect('/')

        context = {
        'signup_form':signup_form,
        }

        return render(request, 'about.html', context)

CreateCard/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponseRedirect
from django.contrib.auth import login as auth_login
from .models import ToDoModel as TDM
from twilio.rest import Client
from django.contrib import messages
from datetime import datetime as dt
from threading import Timer
from django.conf import settings
from twilio.rest import Client

# Create your views here.

class Index(View):
    def create_and_send_msg(self, to_do, number):
        # Find these values at https://twilio.com/user/account
        account_sid = settings.TWILIO_ACCOUNT_SID
        # print(settings.TWILIO_ACCOUNT_SID)
        auth_token = settings.TWILIO_AUTH_TOKEN
        # print(settings.TWILIO_AUTH_TOKEN)
        message = to_do

        client = Client(account_sid, auth_token)

        client.api.account.messages.create(
            to=number,
            from_=settings.TWILIO_CALLER_ID,
            body=message)

    def get(self, request, *args, **kwargs):
        now = dt.now()
        context = {
            'min_date':now.date(),
        }

        return render(request, 'create_card.html', context)

    def post(self, request, *args, **kwargs):
        to_do = request.POST.get("to_do")
        time = request.POST.get("time")
        name = request.POST.get("name")
        phone_number = request.POST.get("phone_number")

        number = "+91" + phone_number

        test_date = time[:10] # extract date from string
        test_time = time[11:] # extract time from string

        test_date = dt.strptime(test_date, "%Y-%m-%d") # convert string date in date object in given format
        test_time = dt.strptime(test_time, "%H:%M") # convert string time in time object in given format

        now = dt.now()
        now = dt.strptime(str(now), '%Y-%m-%d %H:%M:%S.%f')
        time = dt.strptime(time.replace('T', " "), '%Y-%m-%d %H:%M')
        delay = (time - now).total_seconds()

        now = now.replace(microsecond=0)
        #only save in database if created today
        if test_date.date() < now.date():
            messages.error(request, "You can't create cards with date in past.")

        elif test_date.date() == now.date():

            if test_time.time() < now.time():
                messages.error(request, "You must provide time greater than current time.")

            else:
                a = TDM(name=name, time=time, to_do=to_do, phone_number=number)
                a.save()
                messages.success(request, "Card is created successfully")
                # print("delay: ", delay)
                Timer(delay, self.create_and_send_msg, [to_do, number]).start()

        else:
            a = TDM(name=name, time=time, to_do=to_do, phone_number=number)
            a.save()
            messages.success(request, "Card is created successfully")
            Timer(delay, self.create_and_send_msg, [to_do, number]).start()

        return render(request, 'create_card.html', {})

class ViewCard(View):
    def get(self, request, *args, **kwargs):
        cardsObj = TDM.objects.all()
        context = {
            'cardsObj' : cardsObj,
        }
        return render(request, 'view_card.html', context)

Test/views.py
from django.shortcuts import render
from django.views import View
# Create your views here.

class Test(View):
    def get(Self, request, *args, **kwargs):
        b = PD.objects.filter(user_id=request.user)
        for a in b:
            print(a.number)
            phone_number = a.number
        context = {
            'phone_number':phone_number,
        }
        
        return render(request, 'test.html', context)

About/templates/about.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load staticfiles %}

{% block nav %}

    <li class="nav-item">
      <a class="nav-link my_nav_text btn-social" href="#">LOGIN</a>
    </li>

{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="card" style="height: 32rem; width: 25rem; overflow-y: scroll;">
                <div class="card-header" style="background-color: #F63837 !important; color: white">SIGN UP</div>
                <div class="card-body">
                    <form method="POST" action=''>{% csrf_token %}
                        {{ signup_form|crispy }}
                        <input type="submit" class="btn btn-primary" value="SIGN UP" style="background-color: #F63837 !important; border-color: beige;"/>
                    </form>
                </div>
            </div>
            <div class="card ml-3" style="height: 32rem; width: 43rem;">
                <img class="card-img-top" src="{% static 'create_card/img/Demo.jpg' %}" alt="Card image">
                <div class="card-body">
                    <strong>An unique way to manage your daily activities. Get a SMS reminder for all of your
                    activities. Sign Up and Enjoy</strong>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

CreateCard/templates/create_card.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load staticfiles %}

{% block content %}

<style>
    .create-card-btn{
        background-color: #F63837 !important;
        color: white !important;
        border-color: beige;
        margin-left: 13rem;
    }
    .mod-header{
        text-align: center;
        background-color: #F63837;
        color: white;
        opacity: .79;
        font-size: 23px;
    }
    .mod-card-btn{
        background-color: #F63837 !important;
        color: white;
        border-color: beige;
    }
    .my-jumbo{
        margin-top: 4rem;
        background-color: blanchedalmond;;
    }
    .text{
        text-align: center;
    }

</style>



<!-- Card -->
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6">
    <a class="btn btn-primary create-card-btn" data-toggle="modal" data-target="#exampleModal"
    role="button">CREATE CARD</a>
  </div>
  <div class="col-sm-3"></div>
</div>



<!-- Django messages -->
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div
    {% if message.tags == "success" %} class="alert alert-success"
    {% elif message.tags == "error" %} class="alert alert-danger"
    {% endif %}>
        <strong>{{ message }}</strong>
    </div>
    {% endfor %}
</ul>
{% endif %}

<!-- Modal -->

<div class="modal fade" id="exampleModal" tabaccount="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header mod-header">
                <h5 class="modal-title" id="exampleModalLabel">CREATE CARD</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
            </div>

            <div class="modal-body">
                <form method="POST">{% csrf_token %}
                    <div class="form-group">
                        <label> Full Name </label>
                            <input type="username" class="form-control" name="name"><br>
                        <label> Date and Time</label>
                            <input type="datetime-local" class="form-control" name="time"><br>
                        <label for="todo">Type to do</label>
                            <textarea class="form-control" id="todo" rows="3" name="to_do"></textarea><br>
                        <label for="phone_number">Mobile Number</label>
                            <input type="number" class="form-control" id="phone_number" name="phone_number">
                    </div>

                    <hr class="my-4">

                    <button type="button" class="btn btn-secondary mod-card-btn" data-dismiss="modal">CLOSE</button>
                    <input type="submit" class="btn btn-primary mod-card-btn" value="CREATE"/>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

CreateCard/templates/view_card.html
{% extends 'base.html' %}

{% block content %}

<style>
.jumbo{
	background-color: white;
    width: 15rem;
    margin-right: 1rem;
    box-shadow: 0 19px 38px rgba(0, 0, 0, 0.3), 0 15px 12px rgba(0, 0, 0, 0.22);
}

.text{
    text-align: center;
}
</style>

<h1> Cards </h1>
<hr class="my-4">

<div class="container">
	<div class="row">
		{% for card in cardsObj %}
			<div class="jumbotron jumbo">
				Belongs to<strong> {{ card.name }}</strong><br>
				Scheduled at:<strong> {{card.time}}</strong>
			</div>
		{% endfor %}
	</div>
</div>

{% endblock %}

Test/templates/test.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
	<p> {{ phone_number }} </p>
</div>

{% endblock %}

templates/base.html
{% load static %}
{% load staticfiles %}

<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'create_card/css/style.css' %}">

        <style>
            .body{
                background-image: url("{% static 'create_card/img/1.jpg' %}");
            }
            .my-nav-bar{
                background-color: #F63837 !important;
                opacity: 0.79;
            }
            .my_nav_text{
                color:white !important;
            }
            .my_dropdown{
                margin-right: 37px;
            }
        </style>

        <title>2do</title>
    </head>

<body class="body">
        <!-- <div class='container'> -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light my-nav-bar">
        <div class="container-fluid">
            <div class-'navbar-header'>
                <a class="navbar-brand my_nav_text btn-social" href="#">WELCOME TO 2DO</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span></button>
            </div>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                    <a class="nav-link my_nav_text btn-social" href="{% url 'create-card:index' %}">HOME<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link my_nav_text btn-social" href="{% url 'create-card:view' %}">VIEW CARDS</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <br>

    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/psudo_base.html
{% load static %}
{% load staticfiles %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>

    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>